name: CI Pipeline

on:
  push:
    branches:
      - main  # or master depending on your default branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Specify the version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests

      # Step 5: Upload test results (optional)
      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.xml
